version: "3"
services:
  mysql:
    image: "mysql/mysql-server:${MYSQL_VERSION}"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - jamfnet
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    restart: unless-stopped
    volumes:
      - ./${JAMF_PRO_VERSION}/mysql-data-${MYSQL_VERSION}:/var/lib/mysql
  jamfpro:
    image: "jamf/jamfpro:${JAMF_IMAGE_VERSION}"
    depends_on:
      - mysql
    networks:
      - jamfnet
    ports:
      - "80:8080"
    environment:
      DATABASE_USERNAME: "${MYSQL_USER}"
      DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
      DATABASE_HOST: "mysql"
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./${JAMF_PRO_VERSION}/ROOT.war:/data/ROOT.war
      - ./wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    command:
      - /usr/local/bin/wait-for-it.sh
      - --timeout=0
      - mysql:3306
      - --
      - /startup.sh
networks:
  jamfnet:
    driver: bridge
