version: "3"
services:
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - jamfnet
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    restart: unless-stopped
    volumes:
      - ./${JAMF_PRO_VERSION}/mysql-data:/var/lib/mysql
  jamfpro:
    image: "jamf/jamfpro:${JAMF_IMAGE_VERSION}"
    networks:
      - jamfnet
    ports:
      - "80:8080"
    environment:
      DATABASE_USERNAME: "${MYSQL_USER}"
      DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
      DATABASE_HOST: "mysql"
    depends_on:
      - mysql
    restart: unless-stopped
    volumes:
      - ./${JAMF_PRO_VERSION}/ROOT.war:/data/ROOT.war
networks:
  jamfnet:
    driver: bridge
